name: viralinstabot
region: fra
services:
- name: bot
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/viralinstabot
    branch: main
    deploy_on_push: true
  build_command: |
    pip install --no-cache-dir -r requirements.txt
  run_command: python -m src.bot.main
  environment_slug: python
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  envs:
  - key: ENV
    value: production
  - key: DEBUG
    value: "False"
  - key: TELEGRAM_BOT_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: APIFY_API_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DAILY_LIMIT
    value: "10"
  - key: MONTHLY_LIMIT
    value: "10"
  - key: CACHE_DURATION_MINUTES
    value: "60"
  - key: MAX_CONCURRENT_TASKS
    value: "3"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
    success_threshold: 1
  routes:
  - path: /
domains:
- domain: viralinstabot.example.com
  type: PRIMARY